COMPILER= javac
JRE= java
FILES= ProducerConsumer.java Producer.java Consumer.java Buffer.java
EXE= ProducerConsumer
name = Aly-Ammar-HW5
all: 
	$(COMPILER) $(FILES)
run: 
	$(JRE) $(EXE)
clean: 
	rm *.class
package:
	tar -cvzf $(name) *.java *.txt Makefile